            - name: CycloneDX Python Generate SBOM
  # You may pin to the exact commit or the version.
  # uses: CycloneDX/gh-python-generate-sbom@39fe80937489538e12de5a7b427e078649ec44bb
  uses: CycloneDX/gh-python-generate-sbom@v2.0.0
  with:
    # The path to a pip requirements file
    input: # optional, default is ./dev/requirements.txt
    # Output filename
    output: # optional, default is ./bom.xml
    # Output format
    format: # optional, default is xml
